### ISSUE TITLE
Unwinding follow-up to-do list

### ISSUE THREAD

**Issue by kevinaboos** [theseus-os/Theseus#199]
Now that the basics of unwinding have landed in the main branch (see #197), there are a few extra things that we don't want to forget:

- [x] Create a default stack tracing provider based on DWARF/unwinding information. Add an improved interface for custom functions while iterating over stack frames, and then using that new stack iterator function, implement another convenience fn that allows a `Write`r trait object to be passed in for printing rather than hardcoding it to the log. Added by #203.

- [x] Stop setting the force frame pointers compiler option by default. On a related note, gate the `stack_trace_using_frame_pointers()` behind a cfg option based on that compiler flag (if possible). Fixed by #202.

- [ ] Change the way that `Task::kill()` works, such that killing another task will "inject" a panic into that other task rather than just marking it as killed immediately. This will force it to undergo unwinding itself and be properly cleaned up. 

- [x] Trigger stack unwinding upon a machine exception, not just a panic. (Partially address in #204)
